### ISSUE TITLE
Support for Libravatar mugshot

### ISSUE THREAD

**Issue by bignose-debian** [django-userena-ce/django-userena-ce#133]
[Libravatar](https://www.libravatar.org/) is a federated protocol for people to claim their avatar, hosted on a server of their choice.

Please bring Libravatar support on an equal footing with Gravatar.

**Comment by bignose-debian** [comment]
I have made a start at this, in my personal fork repository see the branch https://git.sr.ht/~bignose/django-userena-ce/tree/feature/libravatar

This currently should merge cleanly to the ‘master’ branch.

**Comment by jmsmkn** [comment]
Thank you for the suggestion but I don't really want to add any more configuration options or features to this project.
