### ISSUE TITLE
clean_expired fails when a user has no Userena signup

### ISSUE THREAD

**Issue by Steckelfisch** [django-userena-ce/django-userena-ce#135]
it also fails with 'Cannot delete or update a parent row: a foreign key constraint ', but that probably is because of my local database design.

it is quite possible that this issue only occurs because of the way (and time) of Userena implementation in my project.
Userena was added after the project was started.

I have created a fix that will report the users with errors (and database message if applicable).

**Comment by jmsmkn** [comment]
I think the way to solve this is to create a `UserenaSignUp` for every user. If you have another way of signing up, eg, through social auth, you should create a `UserenaSignUp` object and set the verification status accordingly.
