### ISSUE TITLE
Certain usernames break userena

### ISSUE THREAD

**Issue by boatcoder** [django-userena-ce/django-userena-ce#140]
`accounts/<username>` is the bare profile url as well as some other combinations to complete signup, etc....
a username of `signup` or `signin` or `signout` plus a few others break the pattern.  Not terribly important but it does make me want to go signup for some websites with these names :-)

This could be fixed by using `/profile/<username>` (or any prefix really) into the urls.py.  Wouldn't even have to change code thanks to named URLs.

BUT it would break LOGIN_REDIRECT_URL unless /accounts/profile showed the profile of the currently logged in individual.

Nothin critical, but it could be fixed.

**Comment by jmsmkn** [comment]
Huh, I would have thought those would have been excluded by the regex matching:

https://github.com/django-userena-ce/django-userena-ce/blob/970ca25ca367112625933bd61a0ba745b052692e/userena/urls.py#L127

The original repo has been archived and issues removed (https://github.com/bread-and-pepper/django-userena), but these commits suggest it was an issue in the past too: 111b7329ab0785420180f62d67cb3b65cab421e5, 93699f3dc974f3f09921ae3f7da3b82d9b214a7d, and originally introduced here f7b709aed5d819d04a8f77450feb2eadb4893287 but without a test for it.

I don't think that a change to the paths is necessary, but a test for this matching (any another usernames that would break this) and PR would be welcome.

**Comment by boatcoder** [comment]
OK
