### ISSUE TITLE
Read the doc links not working 

### ISSUE THREAD

**Issue by redblackeagleman** [django-userena-ce/django-userena-ce#144]
Hey there,

Thank you for your work. Was looking to learn more about the tool and all the links pointing to CE edition in Read The Docs say “this page does not exist “.
 Maybe I should be looking someplace else?

Thanks in advance!

![5346E399-4FB2-48BE-8AEF-1096E4D6772F](https://user-images.githubusercontent.com/1653069/154934035-2fe40ceb-a1df-40b7-afd5-2370cb4e683b.jpeg)

**Comment by jmsmkn** [comment]
They have moved to GitHub pages https://django-userena-ce.github.io/django-userena-ce/index.html

All links in this repo should have been updated, let me know if there are any that I missed.

**Comment by redblackeagleman** [comment]
Thank you for prompt response and resolution.
