### ISSUE TITLE
Is there are real "reason" 4.1+ isn't supported

### ISSUE THREAD

**Issue by boatcoder** [django-userena-ce/django-userena-ce#147]
Not seeing any open issues on this but this limit in pyproject.toml

```
Django = ">=3.2,<4.1"
```

Is there anything that needs work or just adjusting the TOX testing setup?

**Comment by jmsmkn** [comment]
It's untested. A PR to update tox, pyproject, the documentation and fix any issues would be welcome, e.g. #138
