### ISSUE TITLE
Multiple Leaf Nodes in the Migration Path

### ISSUE THREAD

**Issue by ambsw-technology** [django-userena-ce/django-userena-ce#17]
I'm seeing the following on both 3.1 and 4.0:

    CommandError: Conflicting migrations detected; multiple leaf nodes in the migration graph: (0002_auto_20180205_1858, 0002_auto_20171130_0921 in userena).
    To fix them run 'python manage.py makemigrations --merge'

**Comment by jmsmkn** [comment]
Only `0002_auto_20171130_0921` exists in the distribution and this does not occur on a fresh install. Did you run a separate makemigrations on Feb 5th and apply this to your database? Is the original userena still installed in your environment?

**Comment by ambsw-technology** [comment]
I installed `ce` first before uninstalling the original.  That may have created a legacy file.  I'm going to close as I'm not sure how the extra migration was created in the first place (as it isn't in the original package either).

**Comment by jackton1** [comment]
An alternative to resolve this would be to use [django-migration-fixer](https://github.com/tj-django/django-migration-fixer)

**Comment by jmsmkn** [comment]
> An alternative to resolve this would be to use [django-migration-fixer](https://github.com/tj-django/django-migration-fixer)

Not really. The solution to this issue which was resolved 3 years ago was to uninstall the package that this one replaces.
