### ISSUE TITLE
Storing mugshot in database

### ISSUE THREAD

**Issue by JamesWilmot** [django-userena-ce/django-userena-ce#21]
Would be extremely convenient if there was ability to specify more sophisticated storage backend ie database as opposed to just offering a file backend.

I wouldn't mind tackling this personally but might need a few pointers to get started. 

Thanks for maintaining this project!

**Comment by jmsmkn** [comment]
Hi! Thanks for your interest - I don't think that storing the images in the database is a good approach performance wise. I think that this project works well with [django-storages](https://github.com/jschneier/django-storages), so maybe one of their backends will work better for you?
