### ISSUE TITLE
After django 1.7, some language code has been replaced.

### ISSUE THREAD

**Issue by acer1832a** [django-userena-ce/django-userena-ce#64]
I'm use django-userena-ce with django 2.1.7.
I found that text of default pages is not translate to chinese, but there is "zh-TW" and "zh-CN" folder in "locale" folder and "django.po" has corresponding text.
After django 1.7, the language code has been replaced, and been deprecated in django 1.9.
So, I copy "zh-TW" folder and rename the folder name to "zh-hant", and restart django. It work and pages is show corresponding Chinese text.
Could you fix this three language code, please?

https://docs.djangoproject.com/en/2.2/releases/1.7/#language-codes-zh-cn-zh-tw-and-fy-nl

**Comment by jmsmkn** [comment]
I have released 4.1.1 which should fix this issue.
