### ISSUE TITLE
How to work without username field?

### ISSUE THREAD

**Issue by Guest007** [django-userena-ce/django-userena-ce#84]
As I understand - I can't use customized user model (without username field - use email instead). I see many hardcoded usings of username in code.
Am I right, or I missed the way to do this?

**Comment by jmsmkn** [comment]
It doesn't look like it, the use of `username` looks pretty baked in. I am only keeping this package alive as I use it in an existing project and have no plans to add this. However, PRs would be welcome if someone wants to add this.
